# Generated by Django 6.0.1 on 2026-02-10 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('est_important', models.BooleanField(default=False)),
                ('est_archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('note_publiee', 'Note publiée'), ('rattrapage', 'Rattrapage programmé'), ('decision', 'Décision publiée'), ('inscription', 'Inscription validée'), ('rappel', 'Rappel important'), ('securite', 'Alerte sécurité'), ('systeme', 'Message système')], default='systeme', max_length=20)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('succes', 'Succès'), ('avertissement', 'Avertissement'), ('urgent', 'Urgent')], default='info', max_length=15)),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('lien', models.URLField(blank=True, null=True)),
                ('donnees', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires au format JSON')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
