version: "3.9"

services:
    backend:
        build: ./backend
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app/
    
    frontend:
        build: ./Frontend
        command: ["npm", "run", "dev"]
        ports:
            - "8080:8080"
        volumes:
            - ./Frontend:/app
            
        