# Generated by Django 6.0.1 on 2026-02-10 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_cc', models.FloatField(blank=True, help_text='Note de contrôle continu (30%)', null=True)),
                ('note_sn', models.FloatField(blank=True, help_text='Note de session normale (70%)', null=True)),
                ('note_ra', models.FloatField(blank=True, help_text='Note de rattrapage si applicable', null=True)),
                ('note_finale', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('rattrapage', 'Doit passer le rattrapage'), ('admis_ra', 'Admis après rattrapage'), ('redouble', 'Redouble la matière'), ('valide', 'Matière validée')], max_length=15)),
                ('mention', models.CharField(blank=True, choices=[('TB', 'Très Bien'), ('B', 'Bien'), ('AB', 'Assez Bien'), ('P', 'Passable'), ('I', 'Insuffisant')], max_length=2, null=True)),
                ('date_decision', models.DateField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Décision Finale',
                'verbose_name_plural': 'Décisions Finales',
                'ordering': ['-date_decision'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('statut', models.CharField(choices=[('rattrapage', 'Rattrapage'), ('valide', 'Valide'), ('non_valide', 'Non Valide')], default='non_valide', max_length=10)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
    ]
