# Generated by Django 6.0.1 on 2026-02-03 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ancienne_valeur', models.FloatField()),
                ('nouvelle_valeur', models.FloatField()),
                ('raison', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historique Note',
                'verbose_name_plural': 'Historiques Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_note', models.CharField(choices=[('CC', 'Contrôle Continu'), ('SN', 'Session Normale'), ('RA', 'Rattrapage')], max_length=2)),
                ('valeur', models.FloatField(help_text='Note sur 20', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('est_validee', models.BooleanField(default=False, help_text='La note a été validée par le responsable')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='DecisionFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_cc', models.FloatField(blank=True, help_text='Note de contrôle continu (30%)', null=True)),
                ('note_sn', models.FloatField(blank=True, help_text='Note de session normale (70%)', null=True)),
                ('note_ra', models.FloatField(blank=True, help_text='Note de rattrapage si applicable', null=True)),
                ('note_finale', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('rattrapage', 'Doit passer le rattrapage'), ('admis_ra', 'Admis après rattrapage'), ('redouble', 'Redouble la matière'), ('valide', 'Matière validée')], max_length=15)),
                ('mention', models.CharField(blank=True, choices=[('TB', 'Très Bien'), ('B', 'Bien'), ('AB', 'Assez Bien'), ('P', 'Passable'), ('I', 'Insuffisant')], max_length=2, null=True)),
                ('date_decision', models.DateField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_finale', to='academic.inscription')),
            ],
            options={
                'verbose_name': 'Décision Finale',
                'verbose_name_plural': 'Décisions Finales',
                'ordering': ['-date_decision'],
            },
        ),
    ]
