# Generated by Django 6.0.1 on 2026-02-17 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('grade', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionfinale',
            name='prise_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_prises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.etudiant'),
        ),
        migrations.AddField(
            model_name='grade',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.evaluation'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('evaluation', 'etudiant')},
        ),
    ]
