# Generated by Django 6.0.1 on 2026-02-03 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('grade', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionfinale',
            name='prise_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_prises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquenote',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='controle_continu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.controlecontinu'),
        ),
        migrations.AddField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.etudiant'),
        ),
        migrations.AddField(
            model_name='note',
            name='rattrapage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.rattrapage'),
        ),
        migrations.AddField(
            model_name='note',
            name='saisie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to='users.enseignant'),
        ),
        migrations.AddField(
            model_name='note',
            name='session_normale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.sessionnormale'),
        ),
        migrations.AddField(
            model_name='note',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquenote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='grade.note'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('controle_continu__isnull', False)), fields=('controle_continu', 'etudiant'), name='unique_note_cc'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('session_normale__isnull', False)), fields=('session_normale', 'etudiant'), name='unique_note_sn'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('rattrapage__isnull', False)), fields=('rattrapage', 'etudiant'), name='unique_note_ra'),
        ),
    ]
