# Generated by Django 6.0.1 on 2026-02-10 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('department', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='directeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to='users.enseignant'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='department.departement'),
        ),
        migrations.AddField(
            model_name='filiereuniteenseignement',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites_enseignement_filiere', to='department.filiere'),
        ),
        migrations.AddField(
            model_name='filiereuniteenseignement',
            name='unite_enseignement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres_associees', to='academic.uniteenseignement'),
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('departement', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='filiereuniteenseignement',
            unique_together={('filiere', 'unite_enseignement')},
        ),
    ]
