# Generated by Django 6.0.1 on 2026-02-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='chef_filiere',
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='credit_total',
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='duree_annees',
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='est_actif',
        ),
    ]
