# Generated by Django 6.0.1 on 2026-02-10 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('department', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteenseignement',
            name='enseignant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='users.enseignant'),
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='filiere',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unites_enseignement', to='department.filiere'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.uniteenseignement'),
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('annee_academique', 'numero')},
        ),
    ]
